# Generated by Django 4.2.20 on 2026-08-26 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('endereco', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('data_desejada', models.DateField(blank=True, null=True, verbose_name='Data desejada')),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('RECEBENDO_ORCAMENTOS', 'Recebendo orçamentos'), ('ORCAMENTO_ACEITO', 'Orçamento aceito'), ('EM_EXECUCAO', 'Em execução'), ('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=30, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='servicos.categoria', verbose_name='Categoria')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='usuarios.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Solicitação',
                'verbose_name_plural': 'Solicitações',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SolicitacaoFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='solicitacoes/', verbose_name='Imagem')),
                ('data_cadastro', models.DateTimeField(auto_now_add=True, verbose_name='Data de cadastro')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='solicitacoes.solicitacao', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Foto da solicitação',
                'verbose_name_plural': 'Fotos das solicitações',
                'ordering': ['data_cadastro'],
            },
        ),
    ]
