# Generated by Django 4.2.20 on 2026-08-26 10:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('solicitacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('descricao', models.TextField(verbose_name='Descrição do orçamento')),
                ('prazo_execucao', models.PositiveIntegerField(blank=True, help_text='Prazo em dias.', null=True, verbose_name='Prazo de execução')),
                ('validade', models.PositiveIntegerField(blank=True, help_text='Validade do orçamento em dias.', null=True, verbose_name='Validade')),
                ('status', models.CharField(choices=[('ENVIADO', 'Enviado'), ('ACEITO', 'Aceito'), ('RECUSADO', 'Recusado'), ('CANCELADO', 'Cancelado'), ('EXPIRADO', 'Expirado')], default='ENVIADO', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orcamentos', to='usuarios.profissional', verbose_name='Profissional')),
                ('solicitacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos', to='solicitacoes.solicitacao', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.AddConstraint(
            model_name='orcamento',
            constraint=models.UniqueConstraint(fields=('solicitacao', 'profissional'), name='unique_orcamento_solicitacao_profissional'),
        ),
    ]
