# Generated by Django 4.2.20 on 2026-08-26 12:04

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('solicitacoes', '0002_orcamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contratacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor contratado')),
                ('percentual_comissao', models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Percentual de comissão')),
                ('valor_comissao', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor da comissão')),
                ('valor_profissional', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor do profissional')),
                ('status', models.CharField(choices=[('AGUARDANDO_PAGAMENTO', 'Aguardando pagamento'), ('PAGAMENTO_CONFIRMADO', 'Pagamento confirmado'), ('EM_EXECUCAO', 'Em execução'), ('SERVICO_CONCLUIDO', 'Serviço concluído'), ('PAGAMENTO_LIBERADO', 'Pagamento liberado'), ('CANCELADA', 'Cancelada')], default='AGUARDANDO_PAGAMENTO', max_length=30, verbose_name='Status')),
                ('data_contratacao', models.DateTimeField(auto_now_add=True, verbose_name='Data da contratação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratacoes', to='usuarios.cliente', verbose_name='Cliente')),
                ('orcamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contratacao', to='solicitacoes.orcamento', verbose_name='Orçamento')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratacoes', to='usuarios.profissional', verbose_name='Profissional')),
                ('solicitacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='contratacao', to='solicitacoes.solicitacao', verbose_name='Solicitação')),
            ],
            options={
                'verbose_name': 'Contratação',
                'verbose_name_plural': 'Contratações',
                'ordering': ['-data_contratacao'],
            },
        ),
    ]
