# Generated by Django 4.2.20 on 2026-08-26 12:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
        ('solicitacoes', '0003_contratacao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Valor')),
                ('metodo', models.CharField(choices=[('PIX', 'PIX'), ('CARTAO', 'Cartão'), ('BOLETO', 'Boleto')], max_length=20, verbose_name='Método de pagamento')),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PROCESSANDO', 'Processando'), ('APROVADO', 'Aprovado'), ('RECUSADO', 'Recusado'), ('CANCELADO', 'Cancelado'), ('ESTORNADO', 'Estornado')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('identificador_transacao', models.CharField(blank=True, help_text='Identificador fornecido pelo gateway de pagamento.', max_length=255, verbose_name='Identificador da transação')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('data_pagamento', models.DateTimeField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='usuarios.cliente', verbose_name='Cliente')),
                ('contratacao', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento', to='solicitacoes.contratacao', verbose_name='Contratação')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
