# Generated by Django 4.2.20 on 2026-08-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_profissional_mercado_pago_connected_and_more'),
        ('solicitacoes', '0004_pagamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(choices=[('MERCADO_PAGO', 'Mercado Pago')], default='MERCADO_PAGO', max_length=30, verbose_name='Gateway')),
                ('access_token', models.TextField(verbose_name='Access Token')),
                ('refresh_token', models.TextField(blank=True, null=True, verbose_name='Refresh Token')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiração do token')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_conexao', models.DateTimeField(auto_now_add=True, verbose_name='Data da conexão')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última atualização')),
                ('profissional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_gateway', to='usuarios.profissional', verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Conta de gateway',
                'verbose_name_plural': 'Contas de gateway',
            },
        ),
    ]
