# Generated by Django 4.2.20 on 2026-08-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitacoes', '0005_contagateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='mercado_pago_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID Mercado Pago'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='mercado_pago_status',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Mercado Pago'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='mercado_pago_status_detail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Detalhe do status Mercado Pago'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='qr_code',
            field=models.TextField(blank=True, null=True, verbose_name='PIX Copia e Cola'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='qr_code_base64',
            field=models.TextField(blank=True, null=True, verbose_name='QR Code Base64'),
        ),
        migrations.AddField(
            model_name='pagamento',
            name='ticket_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL do pagamento'),
        ),
    ]
