# Generated by Django 4.2.20 on 2026-08-30 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('solicitacoes', '0006_pagamento_mercado_pago_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitacoes', to='categorias.categoria', verbose_name='Categoria'),
        ),
    ]
