"""
Django settings for marketplace_servicos project.

Generated by 'django-admin startproject' using Django 4.2.20.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

from dotenv import load_dotenv
from decouple import config


# ==========================================================
# BASE DIR
# ==========================================================

BASE_DIR = Path(__file__).resolve().parent.parent

# Carrega o .env localizado na raiz do projeto
load_dotenv(BASE_DIR / ".env")


# ==========================================================
# CONFIGURAÇÕES BÁSICAS
# ==========================================================

SECRET_KEY = 'django-insecure-r9$ifnigpnz-et!=+ev8&#r!-(^)^i5jw4oeo%v&e&+4-%g(kj'

DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".ngrok-free.dev",
    ".trycloudflare.com",
]


# ==========================================================
# CSRF / TÚNEL
# ==========================================================

CSRF_TRUSTED_ORIGINS = [
    "https://handles-cholesterol-student-antibody.trycloudflare.com",
]


# ==========================================================
# APPLICATION DEFINITION
# ==========================================================

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'usuarios',
    'servicos',
    'solicitacoes',
    'categorias',
    'relatorios_administrativos',
    'ajuda',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'marketplace_servicos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'marketplace_servicos' / 'templates',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'marketplace_servicos.wsgi.application'


# ==========================================================
# DATABASE
# ==========================================================

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "marketplace_servicos",
        "USER": "postgres",
        "PASSWORD": "gres4post",
        "HOST": "localhost",
        "PORT": "5432",
    }
}


# ==========================================================
# PASSWORD VALIDATION
# ==========================================================

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'NumericPasswordValidator'
        ),
    },
]


# ==========================================================
# INTERNATIONALIZATION
# ==========================================================

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# ==========================================================
# STATIC / MEDIA
# ==========================================================

STATIC_URL = "static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# ==========================================================
# AUTH USER
# ==========================================================

AUTH_USER_MODEL = "usuarios.Usuario"

LOGIN_URL = "usuarios:login"
LOGIN_REDIRECT_URL = "usuarios:perfil"
LOGOUT_REDIRECT_URL = "usuarios:login"


# ==========================================================
# MERCADO PAGO
# ==========================================================


# ----------------------------------------------------------
# OAuth / Marketplace
#
# Estas credenciais pertencem à aplicação principal
# marketplace_servicos.
#
# São utilizadas para o profissional autorizar o ChamaPro
# a operar sua conta Mercado Pago através do OAuth.
# ----------------------------------------------------------

MERCADO_PAGO_CLIENT_ID = os.getenv(
    "MP_CLIENT_ID",
    ""
)

MERCADO_PAGO_CLIENT_SECRET = os.getenv(
    "MP_CLIENT_SECRET",
    ""
)

MERCADO_PAGO_REDIRECT_URI = os.getenv(
    "MP_REDIRECT_URI",
    ""
)


# ----------------------------------------------------------
# CREDENCIAIS PRINCIPAIS DA APLICAÇÃO
# ----------------------------------------------------------

MERCADO_PAGO_ACCESS_TOKEN = os.getenv(
    "MP_ACCESS_TOKEN",
    ""
)

MP_PUBLIC_KEY = os.getenv(
    "MP_PUBLIC_KEY",
    ""
)


# ----------------------------------------------------------
# ALIASES DO CHECKOUT
#
# Mantidos porque outras partes do projeto podem utilizar
# estes nomes.
# ----------------------------------------------------------

MERCADO_PAGO_CHECKOUT_ACCESS_TOKEN = (
    MERCADO_PAGO_ACCESS_TOKEN
)

MERCADO_PAGO_CHECKOUT_PUBLIC_KEY = (
    MP_PUBLIC_KEY
)


# ==========================================================
# MODO DE TESTE DE PAGAMENTOS
# ==========================================================
#
# True:
#
#   O ChamaPro utiliza o fluxo de teste do Mercado Pago.
#
#   POST:
#       /v1/orders
#
#   Token:
#       MERCADO_PAGO_TEST_ACCESS_TOKEN
#
#   Neste modo utilizaremos os dados de teste do Mercado
#   Pago para simular PIX, inclusive aprovação através
#   do cenário APRO.
#
#   Não movimenta dinheiro real.
#
#
# False:
#
#   O ChamaPro utiliza o fluxo normal do marketplace.
#
#   POST:
#       /v1/payments
#
#   Token:
#       Access Token OAuth do PROFISSIONAL
#
#   Comissão:
#       application_fee
#
#   Este será o modo utilizado posteriormente em produção.
#
# IMPORTANTE:
#
#   Em produção:
#
#       MP_PAGAMENTO_TESTE=False
#
# ==========================================================

MP_PAGAMENTO_TESTE = config(
    "MP_PAGAMENTO_TESTE",
    default=True,
    cast=bool,
)


# ----------------------------------------------------------
# ACCESS TOKEN EXCLUSIVO PARA TESTES
#
# Deve conter o Access Token encontrado em:
#
# Mercado Pago
#   -> Suas integrações
#   -> marketplace_servicos
#   -> Credenciais de teste
#
# O token deve ficar SOMENTE no arquivo .env.
# ----------------------------------------------------------

MERCADO_PAGO_TEST_ACCESS_TOKEN = os.getenv(
    "MP_TEST_ACCESS_TOKEN",
    ""
)
MERCADO_PAGO_WEBHOOK_SECRET = config(
    "MERCADO_PAGO_WEBHOOK_SECRET",
    default=""
)


# ==========================================================
# WHATSAPP (Evolution API / Local)
# ==========================================================

WHATSAPP_API_URL = os.getenv(
    "WHATSAPP_API_URL",
    "http://localhost:8080/message/sendText/sua_instancia"
)

WHATSAPP_API_TOKEN = os.getenv(
    "WHATSAPP_API_TOKEN"
)


# ==========================================================
# E-MAIL SMTP (GMAIL)
# ==========================================================

EMAIL_BACKEND = (
    'django.core.mail.backends.smtp.EmailBackend'
)

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "franciscougulino@gmail.com"
)

EMAIL_HOST_PASSWORD = os.getenv(
    "SENHA_EMAIL",
    ""
)

DEFAULT_FROM_EMAIL = os.getenv(
    "DEFAULT_FROM_EMAIL",
    "franciscougulino@gmail.com"
)


# ==========================================================
# HTTPS VIA CLOUDFLARE / NGROK
# ==========================================================

SECURE_PROXY_SSL_HEADER = (
    'HTTP_X_FORWARDED_PROTO',
    'https'
)

USE_X_FORWARDED_HOST = True

USE_X_FORWARDED_PORT = True


# ==========================================================
# DEFAULT PRIMARY KEY
# ==========================================================

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'