# Generated by Django 4.2.20 on 2026-08-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='mercado_pago_connected',
            field=models.BooleanField(default=False, verbose_name='Mercado Pago conectado'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='mercado_pago_connected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data de conexão Mercado Pago'),
        ),
        migrations.AddField(
            model_name='profissional',
            name='mercado_pago_user_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='ID do usuário Mercado Pago'),
        ),
    ]
