# Generated by Django 4.2.20 on 2026-08-30 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('usuarios', '0002_profissional_mercado_pago_connected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profissional',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='profissionais', to='categorias.categoria', verbose_name='Categorias de Atendimento'),
        ),
    ]
