# Generated by Django 4.2.20 on 2026-09-03 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=170, unique=True, verbose_name='Slug')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('publico', models.CharField(choices=[('todos', 'Todos'), ('cliente', 'Clientes'), ('profissional', 'Profissionais'), ('administrador', 'Administradores')], default='todos', max_length=20, verbose_name='Público')),
                ('icone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ícone')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoria de Ajuda',
                'verbose_name_plural': 'Categorias de Ajuda',
                'ordering': ['ordem', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='ArtigoAjuda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Slug')),
                ('resumo', models.TextField(blank=True, null=True, verbose_name='Resumo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('visualizacoes', models.PositiveIntegerField(default=0, verbose_name='Visualizações')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artigos', to='ajuda.categoriaajuda', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Artigo de Ajuda',
                'verbose_name_plural': 'Artigos de Ajuda',
                'ordering': ['ordem', 'titulo'],
            },
        ),
    ]
