# Generated by Django 4.2.20 on 2026-08-30 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0001_initial'),
        ('servicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='categorias.categoria', verbose_name='Categoria'),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
